//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DauSach()
        {
            this.ChiTietDonMuonSaches = new HashSet<ChiTietDonMuonSach>();
            this.DanhGias = new HashSet<DanhGia>();
            this.LuocSuMuaSaches = new HashSet<LuocSuMuaSach>();
            this.NhanXets = new HashSet<NhanXet>();
        }
    
        public string madausach { get; set; }
        public string tensach { get; set; }
        public string matacgia { get; set; }
        public string manhaxuatban { get; set; }
        public Nullable<int> soluong { get; set; }
        public string bia { get; set; }
        public string tomtat { get; set; }
        public string filesach { get; set; }
        public System.DateTime ngaydang { get; set; }
        public string machude { get; set; }
        public int luotxem { get; set; }
        public int luotmua { get; set; }
        public int luotdownload { get; set; }
        public Nullable<int> giaban { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonMuonSach> ChiTietDonMuonSaches { get; set; }
        public virtual ChuDe ChuDe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuocSuMuaSach> LuocSuMuaSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanXet> NhanXets { get; set; }
    }
}
