//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonMuonSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonMuonSach()
        {
            this.ChiTietDonMuonSaches = new HashSet<ChiTietDonMuonSach>();
        }
    
        public string madonmuonsach { get; set; }
        public string manguoidung { get; set; }
        public System.DateTime ngaydat { get; set; }
        public Nullable<System.DateTime> ngaymuon { get; set; }
        public Nullable<System.DateTime> ngayhentra { get; set; }
        public Nullable<System.DateTime> ngaytra { get; set; }
        public string matrangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonMuonSach> ChiTietDonMuonSaches { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TrangThai TrangThai { get; set; }
    }
}
