//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LIBRARYDATAMODEL : DbContext
    {
        public LIBRARYDATAMODEL()
            : base("name=LIBRARYDATAMODEL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonMuonSach> ChiTietDonMuonSaches { get; set; }
        public virtual DbSet<ChuDe> ChuDes { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DauSach> DauSaches { get; set; }
        public virtual DbSet<DonMuonSach> DonMuonSaches { get; set; }
        public virtual DbSet<LoaiNguoiDung> LoaiNguoiDungs { get; set; }
        public virtual DbSet<LuocSuMuaSach> LuocSuMuaSaches { get; set; }
        public virtual DbSet<LuocSuNapTien> LuocSuNapTiens { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhanXet> NhanXets { get; set; }
        public virtual DbSet<NhaXuatBan> NhaXuatBans { get; set; }
        public virtual DbSet<PhanHoi> PhanHois { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<ThamSo> ThamSoes { get; set; }
        public virtual DbSet<ThongBaoEmail> ThongBaoEmails { get; set; }
        public virtual DbSet<TrangThai> TrangThais { get; set; }
    
        public virtual ObjectResult<sp_timkiemnguoidungdangnhap_Result> sp_timkiemnguoidungdangnhap(string tendangnhap, string matkhau)
        {
            var tendangnhapParameter = tendangnhap != null ?
                new ObjectParameter("tendangnhap", tendangnhap) :
                new ObjectParameter("tendangnhap", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_timkiemnguoidungdangnhap_Result>("sp_timkiemnguoidungdangnhap", tendangnhapParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<sp_phantrangkhosach_Result> sp_phantrangkhosach(Nullable<int> sosachtrongmottrang, Nullable<int> tranghientai, string luachonxapxep)
        {
            var sosachtrongmottrangParameter = sosachtrongmottrang.HasValue ?
                new ObjectParameter("sosachtrongmottrang", sosachtrongmottrang) :
                new ObjectParameter("sosachtrongmottrang", typeof(int));
    
            var tranghientaiParameter = tranghientai.HasValue ?
                new ObjectParameter("tranghientai", tranghientai) :
                new ObjectParameter("tranghientai", typeof(int));
    
            var luachonxapxepParameter = luachonxapxep != null ?
                new ObjectParameter("luachonxapxep", luachonxapxep) :
                new ObjectParameter("luachonxapxep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_phantrangkhosach_Result>("sp_phantrangkhosach", sosachtrongmottrangParameter, tranghientaiParameter, luachonxapxepParameter);
        }
    }
}
