//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuocSuNapTien
    {
        public string maluocsunaptien { get; set; }
        public string manguoidung { get; set; }
        public System.DateTime ngaynap { get; set; }
        public int tiennap { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
