//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.DonMuonSaches = new HashSet<DonMuonSach>();
            this.LuocSuMuaSaches = new HashSet<LuocSuMuaSach>();
            this.LuocSuNapTiens = new HashSet<LuocSuNapTien>();
            this.NhanXets = new HashSet<NhanXet>();
            this.PhanHois = new HashSet<PhanHoi>();
        }
    
        public string manguoidung { get; set; }
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public string hovaten { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string sodienthoai { get; set; }
        public string gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string motangan { get; set; }
        public string anhdaidien { get; set; }
        public string maloainguoidung { get; set; }
        public string khoanguoidung { get; set; }
        public string makichhoat { get; set; }
        public Nullable<int> sotientaikhoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonMuonSach> DonMuonSaches { get; set; }
        public virtual LoaiNguoiDung LoaiNguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuocSuMuaSach> LuocSuMuaSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuocSuNapTien> LuocSuNapTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanXet> NhanXets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
    }
}
